### ISSUE TITLE
Fix misspelling of water

### ISSUE THREAD

**Issue by avnarun** [salcode/gitpractice#5]
As Bruce Lee once said "Be Water, my friend" - https://www.youtube.com/watch?v=APx2yFA0-B4

So, I will fix the misspelling of zzwater to water !!

![be_water_my_friend_an_by_tornaku-d3cx18u](https://cloud.githubusercontent.com/assets/11977062/8152745/0fa29dae-12ef-11e5-8d60-57e2d3a41ea3.jpg)

**Comment by salcode** [comment]
:+1:
